# Generated by Django 4.2.6 on 2023-11-04 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(null=True)),
                ('responsable', models.CharField(max_length=100, null=True)),
                ('operacion', models.CharField(max_length=255, null=True)),
                ('comentarios', models.CharField(blank=True, max_length=255, null=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboards.lead')),
            ],
            options={
                'verbose_name_plural': 'Historial',
            },
        ),
    ]
