# Generated by Django 4.2.2 on 2023-07-22 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0039_catalogo_catalogoempleados_catalogorespuestasbyetapa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, null=True)),
                ('sala', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
