# Generated by Django 4.2.2 on 2023-07-22 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0040_asesor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogorespuestasbyetapa',
            name='etapa',
            field=models.CharField(choices=[('No contactado', 'No contactado'), ('Interaccion', 'Interaccion'), ('Oportunidad', 'Oportunidad'), ('Pedido', 'Pedido')], max_length=50),
        ),
    ]
