# Generated by Django 4.2.2 on 2023-07-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0041_alter_catalogorespuestasbyetapa_etapa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogorespuestasbyetapa',
            name='estado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='catalogorespuestasbyetapa',
            name='tipo',
            field=models.CharField(blank=True, choices=[('normal', 'normal'), ('compra', 'compra'), ('peritaje', 'peritaje')], max_length=50, null=True),
        ),
    ]
