# Generated by Django 4.2.2 on 2023-07-25 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0042_alter_catalogorespuestasbyetapa_estado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asesor',
            options={'verbose_name_plural': 'Asesores'},
        ),
    ]
