# Generated by Django 4.2.2 on 2023-07-25 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0043_alter_asesor_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='asesor',
            name='habilitado',
            field=models.BooleanField(max_length=255, null=True),
        ),
    ]
