# Generated by Django 4.2.2 on 2023-07-25 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0044_asesor_habilitado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asesor',
            name='habilitado',
            field=models.BooleanField(default=True, max_length=255),
            preserve_default=False,
        ),
    ]
