# Generated by Django 4.2.2 on 2023-07-28 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0045_alter_asesor_habilitado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='compania',
            new_name='campania',
        ),
        migrations.AlterField(
            model_name='prospecto',
            name='cliente',
            field=models.BooleanField(null=True),
        ),
    ]
