# Generated by Django 4.2.2 on 2023-07-28 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0046_rename_compania_lead_campania_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='fecha_apertura',
            field=models.DateField(null=True),
        ),
    ]
