# Generated by Django 4.2.2 on 2023-07-28 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0047_alter_lead_fecha_apertura'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoModelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'CatalogoModelo',
            },
        ),
    ]
