# Generated by Django 4.2.2 on 2023-07-29 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0048_catalogomodelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='marcas_interes',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
