# Generated by Django 4.2.2 on 2023-07-29 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0049_alter_lead_marcas_interes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='fecha_apertura',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='prospecto',
            name='fecha_captura',
            field=models.DateTimeField(),
        ),
    ]
