# Generated by Django 4.2.2 on 2023-08-11 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0050_alter_lead_fecha_apertura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='tiempo_primer_contacto',
            field=models.IntegerField(null=True),
        ),
    ]
