# Generated by Django 4.2.2 on 2023-08-11 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0051_lead_tiempo_primer_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='fecha_primer_contacto',
            field=models.DateTimeField(null=True),
        ),
    ]
