# Generated by Django 4.2.2 on 2023-08-14 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0054_historial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historial',
            options={'verbose_name_plural': 'Historial'},
        ),
        migrations.AddField(
            model_name='historial',
            name='lead',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='dashboards.lead'),
            preserve_default=False,
        ),
    ]
