# Generated by Django 4.2.2 on 2023-08-14 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0055_alter_historial_options_historial_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial',
            name='comentarios',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
