# Generated by Django 4.2.2 on 2023-08-15 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0057_alter_historial_responsable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialverificaciones',
            name='id_lead',
        ),
        migrations.AddField(
            model_name='historialverificaciones',
            name='lead',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='dashboards.lead'),
            preserve_default=False,
        ),
    ]
