# Generated by Django 4.2.2 on 2023-08-15 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0058_remove_historialverificaciones_id_lead_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialverificaciones',
            name='reasignado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historialverificaciones',
            name='tipo',
            field=models.CharField(choices=[('venta', 'venta'), ('compra', 'compra'), ('peritaje', 'peritaje')], max_length=50),
        ),
    ]
