# Generated by Django 4.2.2 on 2023-08-15 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0059_alter_historialverificaciones_reasignado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialverificaciones',
            name='responsable_original_lead',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
