# Generated by Django 4.2.2 on 2023-08-17 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0060_alter_historialverificaciones_responsable_original_lead'),
    ]

    operations = [
        migrations.RenameField(
            model_name='retomas',
            old_name='descripcion_vehiculo',
            new_name='modelo',
        ),
        migrations.AddField(
            model_name='retomas',
            name='total',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='retomas',
            name='total_restante',
            field=models.FloatField(default=1000),
            preserve_default=False,
        ),
    ]
