# Generated by Django 4.2.2 on 2023-08-17 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0061_rename_descripcion_vehiculo_retomas_modelo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retomas',
            name='id_lead',
        ),
        migrations.AddField(
            model_name='retomas',
            name='lead',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='dashboards.lead'),
            preserve_default=False,
        ),
    ]
