# Generated by Django 4.2.2 on 2023-08-17 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0062_remove_retomas_id_lead_retomas_lead'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculosintereslead',
            name='id_lead',
        ),
        migrations.AddField(
            model_name='vehiculosintereslead',
            name='lead',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='dashboards.lead'),
            preserve_default=False,
        ),
    ]
