# Generated by Django 4.2.2 on 2023-08-17 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0063_remove_vehiculosintereslead_id_lead_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='comentario',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
