# Generated by Django 4.2.4 on 2023-08-21 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0064_alter_lead_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculosintereslead',
            name='mostrado',
            field=models.BooleanField(null=True),
        ),
    ]
