# Generated by Django 4.2.4 on 2023-08-22 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0065_vehiculosintereslead_mostrado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculosintereslead',
            name='comentario',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehiculosintereslead',
            name='fecha_aprobacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
