# Generated by Django 4.2.4 on 2023-08-31 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0066_alter_vehiculosintereslead_comentario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, null=True)),
                ('tipo', models.CharField(choices=[('Testdrive', 'Testdrive'), ('Peritaje', 'Peritaje'), ('Whatsapp', 'Whatsapp')], max_length=255, null=True)),
                ('cliente', models.CharField(max_length=255, null=True)),
                ('observaciones', models.CharField(max_length=255)),
                ('asesor', models.CharField(max_length=255)),
                ('fecha_hora', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Asesores',
            },
        ),
    ]
