# Generated by Django 4.2.4 on 2023-08-31 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0068_rename_eventos_evento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evento',
            options={},
        ),
        migrations.AlterField(
            model_name='evento',
            name='asesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboards.asesor'),
        ),
    ]
