# Generated by Django 4.2.4 on 2023-08-31 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0069_alter_evento_options_alter_evento_asesor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='asesor',
            field=models.CharField(max_length=255),
        ),
    ]
