# Generated by Django 4.2.4 on 2023-08-31 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0070_alter_evento_asesor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='asesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboards.asesor'),
        ),
    ]
