# Generated by Django 4.2.4 on 2023-09-07 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0072_alter_catalogorespuestasbyetapa_etapa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='marcas_interes',
            field=models.CharField(max_length=3000, null=True),
        ),
    ]
