# Generated by Django 4.2.4 on 2023-09-07 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0073_alter_lead_marcas_interes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospecto',
            name='ciudad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prospecto',
            name='correo_asesor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prospecto',
            name='departamento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prospecto',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prospecto',
            name='ingresos',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prospecto',
            name='interes_deporte',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prospecto',
            name='interes_mascotas',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prospecto',
            name='localidad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prospecto',
            name='profesion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prospecto',
            name='vehiculo_actual',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
