# Generated by Django 4.2.4 on 2023-09-08 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0074_alter_prospecto_ciudad_alter_prospecto_correo_asesor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='fecha_contacto_asesor',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
