# Generated by Django 4.2.4 on 2023-09-11 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0075_alter_lead_fecha_contacto_asesor'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='fecha_hora_reasignacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
