# Generated by Django 4.2.4 on 2023-09-19 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0076_lead_fecha_hora_reasignacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospecto',
            name='contacto_nombre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prospecto',
            name='contacto_telefono',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
