# Generated by Django 4.2.4 on 2023-09-26 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0078_evento_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='tiempo_evento',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
