# Generated by Django 4.2.4 on 2023-09-27 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0079_evento_tiempo_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='tipo',
            field=models.CharField(choices=[('Testdrive', 'Testdrive'), ('Peritaje', 'Peritaje'), ('Whatsapp', 'Whatsapp'), ('Llamada', 'Llamada'), ('Cita Vitrina', 'Cita Vitrina')], max_length=255, null=True),
        ),
    ]
