# Generated by Django 4.2.4 on 2023-09-27 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0080_alter_evento_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='cumplido',
            field=models.BooleanField(null=True),
        ),
    ]
