# Generated by Django 4.2.4 on 2023-09-27 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0081_evento_cumplido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='cumplido',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
