# Generated by Django 4.2.4 on 2023-10-03 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0082_alter_evento_cumplido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='cliente',
            new_name='telefono_cliente',
        ),
    ]
