# Generated by Django 4.2.4 on 2023-10-03 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0083_rename_cliente_evento_telefono_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='fecha_hora_cumplido',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
