# Generated by Django 4.2.4 on 2023-10-06 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0084_evento_fecha_hora_cumplido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiculosintereslead',
            old_name='fecha_aprobacion',
            new_name='fecha',
        ),
    ]
