# Generated by Django 4.2.6 on 2023-10-12 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0085_rename_fecha_aprobacion_vehiculosintereslead_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='fecha_cierre',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
