# Generated by Django 4.2.6 on 2023-10-12 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0086_alter_lead_fecha_cierre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculosintereslead',
            name='precio',
            field=models.FloatField(null=True),
        ),
    ]
