# Generated by Django 4.2.6 on 2023-10-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0087_alter_vehiculosintereslead_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='fecha_cambio_de_etapa',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
