# Generated by Django 4.2.6 on 2023-10-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0088_lead_fecha_cambio_de_etapa'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='tiempo_cambio_de_etapa',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
