# Generated by Django 4.2.6 on 2023-10-17 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0089_lead_tiempo_cambio_de_etapa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='marcas_interes',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
