# Generated by Django 4.2.6 on 2023-10-24 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0090_alter_lead_marcas_interes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospecto',
            name='celular',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
