# Generated by Django 4.2.6 on 2023-10-24 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0091_alter_prospecto_celular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospecto',
            name='fecha_hora_asignacion_asesor',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
