# Django
from django.urls import path
from django.views.generic.base import View

# Views
from dashboards import views

urlpatterns = [
    path(
        route="login",
        view=views.LoginView.as_view(),
        name="login"
    ),
    path(
        route="logout",
        view=views.LogoutView.as_view(),
        name="logout"
    ),
    path(
        route="",
        view=views.CapturaView.as_view(),
        name="captura"
    ),
    path(
        route="captura/<int:pk>",
        view=views.CapturaReasignamientoView.as_view(),
        name="captura_reasignamiento"
    ),
    path(
        route="detalle",
        view=views.DetalleClienteView.as_view(),
        name="detalle"
    ),
    path(
        route="<int:pk>",
        view=views.DetalleClienteNuevoView.as_view(),
        name="detallenuevo"
    ),
    path(
        route="operativo_anfitrion",
        view=views.OperativoAnfitrionView.as_view(),
        name="operativo_anfitrion"
    ),
    path(
        route="operativo_asesor",
        view=views.OperativoAsesorView.as_view(),
        name="operativo_asesor"
    ),
    path(
        route="reportes",
        view=views.ReportesView.as_view(),
        name="reportes"
    ),
    path(
        route="reportes_eventos",
        view=views.ReportesEventosView.as_view(),
        name="reportes_eventos"
    ),
    path(
        route="tiempos",
        view=views.TiemposView.as_view(),
        name="tiempos"
    ),
    path(
        route="anulados",
        view=views.AnuladosView.as_view(),
        name="anulados"
    ),
    path(
        route="modernize",
        view=views.ModernizeView.as_view(),
        name="modernize"
    ),
    path(
        route="modernize2",
        view=views.Modernize2View.as_view(),
        name="modernize2"
    ),
    path(
        route="calendar",
        view=views.CalendarView.as_view(),
        name="calendar"
    ),
    path(
        route="calendar/<int:pk>",
        view=views.CalendarDetailView.as_view(),
        name="calendar_detail"
    ),
]